{
 "title": "4 Golden Signals Dashboard",
 "tags": [ "golden-signals" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Rate test",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m]))",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}