global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['go-backend:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']